defaults:
  - override hydra/launcher: MY_2HRS
  - _self_


hydra:
  launcher: 
    gres: gpu:a100 # 
    # gpus-per-task: rtx8000:1
    mem_gb: 32
    tasks_per_node: 1
    cpus_per_task: 8
    array_parallelism: 3 # I think this means run per job.
    additional_parameters:
      time: 0-03:00:00                               # maximum wall time allocated for the job (D-H:MM:SS)
      # mail-type: ARRAY_TASKS,FAIL,TIME_LIMIT         # events to notify user by email
      # mail-user: ???                                 # email of the user

experiment:
  name: mini_grp
  project: mini-grp
  
batch_size: 128 # how many independent sequences will we process in parallel?
max_block_size: 12 ## Will be overidden by code
vocab_size: 32 ## Will be overidden by code
n_patches: 8
max_iters: 50000
eval_interval: 100
learning_rate: 5e-5
eval_iters: 200
policy:
  action_stacking: 2
  obs_stacking: 3

n_embd: 512
device: "cuda"
testing: true
simEval: false
eval_vid_iters: 2500
gradient_accumulation_steps: 2

sim:
  eval_episodes: 2

# ------------

r_seed: 1337
n_head: 16
n_blocks: 4
dropout: 0.2
action_bins: 7
action_dim: 7
load_action_bounds: true
env:
  action_std: [0.016753544993060053, 0.023366538587021844, 0.020825098821764754, 0.04094312200887319, 0.0450425630283353, 0.07591476573186073, 1.0]
  action_mean: [0.0005073429474377862, 0.0010121935122961018, 0.00047337321896007546, 0.0004149420738629149, -0.0018587493762149167, 0.0020303972612628974, 0.5]
  gripper_closed_std: 1.0

## Model hyperparameters
image_shape: [64, 64, 3]
data_shuffel_interval: 500
dataset: 
  from_name: "/network/datasets/openxembodiment/datasets/bridge/0.1.0/"
  to_name: gberseth/bridge-data-64px-full
  num_episodes: 50
  chunk_size: 50
  buffer_size: 5000
  encode_with_t5: false
  t5_version: "t5-small"
  chars_list:  [' ', ',', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   '!', '?', '"', "'", '(', ')', '-', '_', ':', ';',
   '@', '#', '$', '%', '&', '*', '+', '=', '<', '>', '/', '\\', '|', '~', '`',
   'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 
   'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
  load_dataset: true
  dataset_indicies: {
    "/network/datasets/openxembodiment/datasets/bridge/0.1.0/": {"start": 11, size: 28935, weight: 0.3, dataset_key: "bridge_oxe", scale: 1.0},
    "/network/datasets/openxembodiment/datasets/stanford_robocook_converted_externally_to_rlds/0.1.0": {"start": 0, size: 1000000, weight: 0.3, dataset_key: "stanford_robocook_converted_externally_to_rlds", scale: 1.0},
    "/network/datasets/openxembodiment/datasets/maniskill_dataset_converted_externally_to_rlds/0.1.0": {"start": 0, size: 1000000, weight: 0.3, dataset_key: "maniskill_dataset_converted_externally_to_rlds", scale: 1.0},
    # "/network/projects/real-g-grp/modified_libero_rlds": {"start": 0, size: 1000000, weight: 0.3, dataset_key: "maniskill_dataset_converted_externally_to_rlds", scale: 1.0},
    # "gs://gresearch/robotics/bridge/0.1.0/": {"start": 11, size: 28935, weight: 0.5, dataset_key: "bridge_oxe", scale: 1.0},
    # "gs://gresearch/robotics/stanford_robocook_converted_externally_to_rlds/0.1.0": {"start": 0, size: 1000000, weight: 0.5, dataset_key: "stanford_robocook_converted_externally_to_rlds", scale: 1.0},
    # "gs://gresearch/robotics/maniskill_dataset_converted_externally_to_rlds/0.1.0": {"start": 0, size: 1000000, weight: 0.5, dataset_key: "maniskill_dataset_converted_externally_to_rlds", scale: 1.0},
    # "/network/datasets/openxembodiment/datasets/language_table/0.0.1": {"start": 0, size: 1000000, weight: 0.5, "image_key": "rgb", "text_key": "instruction"},  
    # "/network/datasets/openxembodiment/datasets/kuka/0.1.0": {"start": 0, size: 1000000, weight: 0.5, "image_key": "image", "text_key": "natural_language_instruction", "action_key": "gripper_closedness_action", scale: 0.1},  
  }
  
trim: 1000000
